PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE IF NOT EXISTS subject(id TEXT PRIMARY KEY, name TEXT, accent TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS zone(id TEXT PRIMARY KEY, subject_id TEXT, ord INTEGER, name TEXT, topic TEXT, min_level INTEGER);
CREATE TABLE IF NOT EXISTS item(id INTEGER PRIMARY KEY AUTOINCREMENT, zone_id TEXT, q TEXT, expr TEXT, opts_json TEXT, a INTEGER, hint TEXT, difficulty TEXT, knowledge TEXT);
CREATE TABLE IF NOT EXISTS zone_pokemon(zone_id TEXT, dex INTEGER, name TEXT, type TEXT, rarity TEXT);
CREATE TABLE IF NOT EXISTS content_version(id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id TEXT, built_at TEXT, agent TEXT, source_notes TEXT, status TEXT);
INSERT INTO subject(id,name,accent,status) VALUES('curriculum','5 Menit Matematika','#FFCB05','active') ON CONFLICT(id) DO UPDATE SET name=excluded.name,accent=excluded.accent,status=excluded.status;
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_1','curriculum',1,'Padang Tambah','penjumlahan',1) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_1';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',19,'Rattata','Normal','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',16,'Pidgey','Flying','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',10,'Caterpie','Bug','common');
DELETE FROM item WHERE zone_id='curriculum_1';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','54 + 15 = ?','["68","79","70","69"]',3,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','68 + 68 = ?','["146","136","135","137"]',1,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','56 + 58 = ?','["113","114","115","124"]',1,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','72 + 16 = ?','["98","87","88","89"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','61 + 77 = ?','["138","137","148","139"]',0,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','48 + 37 = ?','["84","86","95","85"]',3,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','42 + 67 = ?','["119","110","108","109"]',3,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','37 + 26 = ?','["64","63","73","62"]',1,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','50 + 25 = ?','["85","76","74","75"]',3,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','67 + 26 = ?','["92","103","93","94"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','81 + 33 = ?','["113","124","114","115"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','21 + 15 = ?','["35","37","36","46"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_2','curriculum',2,'Lembah Kurang','pengurangan',3) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_2';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',21,'Spearow','Flying','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',129,'Magikarp','Water','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',13,'Weedle','Bug','common');
DELETE FROM item WHERE zone_id='curriculum_2';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','63 − 50 = ?','["14","23","12","13"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','99 − 56 = ?','["53","44","42","43"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','95 − 15 = ?','["90","79","80","81"]',2,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','47 − 10 = ?','["36","47","38","37"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','78 − 65 = ?','["14","13","12","23"]',1,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','44 − 19 = ?','["25","26","24","35"]',0,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','57 − 28 = ?','["29","30","28","39"]',0,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','67 − 52 = ?','["16","14","25","15"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','97 − 75 = ?','["23","32","22","21"]',2,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','79 − 25 = ?','["54","53","64","55"]',0,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','63 − 14 = ?','["48","49","50","59"]',1,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','40 − 29 = ?','["12","10","11","21"]',2,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_3','curriculum',3,'Bukit Kali','perkalian',5) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_3';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',52,'Meowth','Normal','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',56,'Mankey','Fighting','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',54,'Psyduck','Water','uncommon');
DELETE FROM item WHERE zone_id='curriculum_3';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','3 × 12 = ?','["24","37","39","36"]',3,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','12 × 4 = ?','["48","44","49","60"]',0,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','7 × 12 = ?','["85","84","91","72"]',1,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','12 × 11 = ?','["121","133","144","132"]',3,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','4 × 10 = ?','["41","30","44","40"]',3,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','4 × 9 = ?','["37","40","36","27"]',2,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','11 × 9 = ?','["110","90","99","100"]',2,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','6 × 7 = ?','["43","42","48","35"]',1,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','9 × 7 = ?','["72","63","56","64"]',1,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','12 × 9 = ?','["99","120","109","108"]',3,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','4 × 7 = ?','["28","21","29","32"]',0,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','3 × 5 = ?','["18","10","16","15"]',3,'Ingat tabel perkalian; kali itu penjumlahan berulang.','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_4','curriculum',4,'Ngarai Bagi','pembagian',8) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_4';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',66,'Machop','Fighting','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',74,'Geodude','Rock','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',27,'Sandshrew','Ground','uncommon');
DELETE FROM item WHERE zone_id='curriculum_4';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','30 ÷ 5 = ?','["6","7","5","8"]',0,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','36 ÷ 3 = ?','["3","12","11","13"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','84 ÷ 12 = ?','["12","7","6","8"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','144 ÷ 12 = ?','["14","12","13","11"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','44 ÷ 4 = ?','["12","10","4","11"]',3,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','49 ÷ 7 = ?','["7","8","9","6"]',0,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','48 ÷ 6 = ?','["7","9","8","6"]',2,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','16 ÷ 2 = ?','["7","8","9","2"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','20 ÷ 4 = ?','["6","5","7","4"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','66 ÷ 11 = ?','["6","5","11","7"]',0,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','120 ÷ 10 = ?','["10","11","13","12"]',3,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','22 ÷ 2 = ?','["2","11","10","12"]',1,'Tanya: dikali berapa biar dapat angka itu?','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_5','curriculum',5,'Telaga Pecahan','pecahan',11) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_5';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',7,'Squirtle','Water','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',4,'Charmander','Fire','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',1,'Bulbasaur','Grass','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',133,'Eevee','Normal','rare');
DELETE FROM item WHERE zone_id='curriculum_5';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/8 − 2/8 = ?','["2/8","6/8","2/16","3/8"]',0,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','6/8 − 1/8 = ?','["7/8","6/8","5/16","5/8"]',3,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','3/5 − 2/5 = ?','["2/5","5/5","1/5","1/10"]',2,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','3/4 − 1/4 = ?','["3/4","4/4","2/4","2/8"]',2,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/10 − 2/10 = ?','["3/10","2/10","6/10","2/20"]',1,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','6/10 + 2/10 = ?','["9/10","8/10","8/20","6/10"]',1,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','6/8 + 1/8 = ?','["7/8","7/16","8/8","6/8"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/8 − 1/8 = ?','["3/16","4/8","3/8","5/8"]',2,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','5/8 + 2/8 = ?','["7/8","5/8","7/16","8/8"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','2/10 − 1/10 = ?','["3/10","2/10","1/20","1/10"]',3,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','2/4 + 1/4 = ?','["3/8","4/4","2/4","3/4"]',3,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','2/4 − 1/4 = ?','["1/8","1/4","2/4","3/4"]',1,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_6','curriculum',6,'Puncak Desimal','desimal',14) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_6';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',25,'Pikachu','Electric','rare');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',63,'Abra','Psychic','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',147,'Dratini','Dragon','rare');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',39,'Jigglypuff','Fairy','uncommon');
DELETE FROM item WHERE zone_id='curriculum_6';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.8 = ?','["1.0","1.1","0.9","2.0"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.1 = ?','["0.2","0.3","0.4","1.3"]',1,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.7 + 0.2 = ?','["1.0","1.9","0.9","0.8"]',2,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.2 = ?','["0.4","0.5","0.3","1.4"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.5 + 0.7 = ?','["1.3","2.2","1.2","1.1"]',2,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.5 + 0.8 = ?','["2.3","1.4","1.3","1.2"]',2,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.9 + 0.5 = ?','["1.4","1.5","1.3","2.4"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.1 + 0.2 = ?','["0.3","1.3","0.2","0.4"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.7 + 0.1 = ?','["0.8","0.9","0.7","1.8"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.7 + 0.9 = ?','["2.6","1.7","1.6","1.5"]',2,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.4 = ?','["1.6","0.5","0.7","0.6"]',3,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.3 + 0.2 = ?','["1.5","0.6","0.5","0.4"]',2,'Sejajarkan koma; jumlahkan per tempat desimal.','hard','');
INSERT INTO content_version(subject_id,built_at,agent,source_notes,status) VALUES('curriculum','2026-06-07T11:11:22.705Z','content-engine','seed.mjs from tools/content-engine/out-math/','active');
COMMIT;