PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE IF NOT EXISTS subject(id TEXT PRIMARY KEY, name TEXT, accent TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS zone(id TEXT PRIMARY KEY, subject_id TEXT, ord INTEGER, name TEXT, topic TEXT, min_level INTEGER);
CREATE TABLE IF NOT EXISTS item(id INTEGER PRIMARY KEY AUTOINCREMENT, zone_id TEXT, q TEXT, expr TEXT, opts_json TEXT, a INTEGER, hint TEXT, difficulty TEXT, knowledge TEXT);
CREATE TABLE IF NOT EXISTS zone_pokemon(zone_id TEXT, dex INTEGER, name TEXT, type TEXT, rarity TEXT);
CREATE TABLE IF NOT EXISTS content_version(id INTEGER PRIMARY KEY AUTOINCREMENT, subject_id TEXT, built_at TEXT, agent TEXT, source_notes TEXT, status TEXT);
INSERT INTO subject(id,name,accent,status) VALUES('curriculum','5 Menit Matematika','#FFCB05','active') ON CONFLICT(id) DO UPDATE SET name=excluded.name,accent=excluded.accent,status=excluded.status;
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_1','curriculum',1,'Padang Tambah','penjumlahan',1) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_1';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',19,'Rattata','Normal','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',16,'Pidgey','Flying','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_1',10,'Caterpie','Bug','common');
DELETE FROM item WHERE zone_id='curriculum_1';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa angka yang hilang?','47 + ? = 75','["27","28","75","29"]',1,'Yang hilang = hasil dikurangi angka yang diketahui.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa angka yang hilang?','41 + ? = 61','["19","20","21","61"]',1,'Yang hilang = hasil dikurangi angka yang diketahui.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 33 kue, lalu ditambah 42 kue lagi. Berapa total kue?','','["74","76","33","75"]',3,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','33 + 78 = ?','["121","110","111","112"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','18 + 37 = ?','["54","56","55","65"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa angka yang hilang?','47 + ? = 92','["44","92","46","45"]',3,'Yang hilang = hasil dikurangi angka yang diketahui.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 32 bola, lalu ditambah 30 bola lagi. Berapa total bola?','','["63","61","62","32"]',2,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa angka yang hilang?','31 + ? = 53','["21","53","22","23"]',2,'Yang hilang = hasil dikurangi angka yang diketahui.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','23 + 19 = ?','["43","42","41","52"]',1,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 18 bola, lalu ditambah 16 bola lagi. Berapa total bola?','','["35","34","18","33"]',1,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','20 + 12 = ?','["32","33","31","42"]',0,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 25 buku, lalu ditambah 9 buku lagi. Berapa total buku?','','["34","35","33","25"]',0,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','69 + 61 = ?','["130","129","140","131"]',0,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 33 permen, lalu ditambah 43 permen lagi. Berapa total permen?','','["33","77","76","75"]',2,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','74 + 89 = ?','["173","164","163","162"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','51 + 61 = ?','["112","122","111","113"]',0,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Ada 33 roti, lalu ditambah 39 roti lagi. Berapa total roti?','','["33","73","71","72"]',3,'Total = jumlah keduanya. Tambahkan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','55 + 24 = ?','["89","78","79","80"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','22 + 88 = ?','["110","109","111","120"]',0,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_1','Berapa hasilnya?','12 + 14 = ?','["36","27","26","25"]',2,'Jumlahkan satuan dulu, lalu puluhan.','easy','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_2','curriculum',2,'Lembah Kurang','pengurangan',3) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_2';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',21,'Spearow','Flying','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',129,'Magikarp','Water','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_2',13,'Weedle','Bug','common');
DELETE FROM item WHERE zone_id='curriculum_2';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','80 − ? = 67','["13","14","12","67"]',0,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Punya 19 bunga, 13 bunga diberikan ke teman. Sisa berapa?','','["32","5","7","6"]',3,'Sisa = punya dikurangi yang diberikan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','64 − ? = 56','["9","56","8","7"]',2,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','68 − 28 = ?','["40","39","50","41"]',0,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','61 − 47 = ?','["24","15","14","13"]',2,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','40 − ? = 7','["34","32","7","33"]',3,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Punya 33 apel, 18 apel diberikan ke teman. Sisa berapa?','','["15","16","51","14"]',0,'Sisa = punya dikurangi yang diberikan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','68 − ? = 52','["16","52","17","15"]',0,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','72 − 56 = ?','["17","16","26","15"]',1,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','95 − 81 = ?','["15","13","24","14"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','68 − 45 = ?','["23","33","24","22"]',0,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','73 − 32 = ?','["40","42","51","41"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','72 − ? = 19','["52","53","54","19"]',1,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Punya 46 roti, 35 roti diberikan ke teman. Sisa berapa?','','["12","81","11","10"]',2,'Sisa = punya dikurangi yang diberikan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','70 − 38 = ?','["42","31","33","32"]',3,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','56 − ? = 24','["24","31","33","32"]',3,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','87 − 75 = ?','["22","12","11","13"]',1,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Punya 48 roti, 12 roti diberikan ke teman. Sisa berapa?','','["60","36","35","37"]',1,'Sisa = punya dikurangi yang diberikan.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa hasilnya?','67 − 35 = ?','["33","32","31","42"]',1,'Kurangi satuan dulu; pinjam dari puluhan bila perlu.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_2','Berapa angka yang hilang?','42 − ? = 5','["5","36","38","37"]',3,'Yang dikurangi = angka awal dikurangi hasilnya.','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_3','curriculum',3,'Bukit Kali','perkalian',5) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_3';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',52,'Meowth','Normal','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',56,'Mankey','Fighting','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_3',54,'Psyduck','Water','uncommon');
DELETE FROM item WHERE zone_id='curriculum_3';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 9 kotak, tiap kotak berisi 5 bola. Berapa total bola?','','["45","36","50","14"]',0,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','8 × ? = 16','["1","3","8","2"]',3,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','7 × 5 = ?','["36","42","35","30"]',2,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 3 kotak, tiap kotak berisi 6 pensil. Berapa total pensil?','','["18","9","15","24"]',0,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','6 × ? = 72','["12","6","13","11"]',0,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','6 × 9 = ?','["45","60","55","54"]',3,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','8 × 9 = ?','["80","63","73","72"]',3,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 2 kotak, tiap kotak berisi 5 kue. Berapa total kue?','','["7","15","8","10"]',3,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 6 kotak, tiap kotak berisi 4 pensil. Berapa total pensil?','','["24","18","10","28"]',0,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','8 × ? = 64','["8","7","64","9"]',0,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','9 × ? = 90','["10","90","9","11"]',0,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','3 × 8 = ?','["27","16","25","24"]',3,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','8 × 12 = ?','["96","84","104","97"]',0,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','10 × ? = 110','["12","10","110","11"]',3,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 8 kotak, tiap kotak berisi 9 bola. Berapa total bola?','','["17","81","72","64"]',2,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 6 kotak, tiap kotak berisi 7 buku. Berapa total buku?','','["42","36","13","49"]',0,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','11 × 4 = ?','["55","44","40","45"]',1,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa angka yang hilang?','4 × ? = 32','["9","4","7","8"]',3,'Yang hilang = hasil dibagi angka yang diketahui.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Berapa hasilnya?','10 × 8 = ?','["80","72","90","81"]',0,'Kali = penjumlahan berulang. Ingat tabel perkalian.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_3','Ada 7 kotak, tiap kotak berisi 6 roti. Berapa total roti?','','["48","42","35","13"]',1,'Total = banyak kotak × isi tiap kotak.','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_4','curriculum',4,'Ngarai Bagi','pembagian',8) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_4';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',66,'Machop','Fighting','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',74,'Geodude','Rock','common');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_4',27,'Sandshrew','Ground','uncommon');
DELETE FROM item WHERE zone_id='curriculum_4';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','77 ÷ 7 = ?','["11","7","12","10"]',0,'Tanya: dikali berapa supaya dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 4 = 6','["24","6","20","28"]',0,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','32 koin dibagi rata ke 4 anak. Tiap anak dapat berapa?','','["9","7","4","8"]',3,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','48 bola dibagi rata ke 8 anak. Tiap anak dapat berapa?','','["6","7","5","8"]',0,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 6 = 6','["42","36","30","6"]',1,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','54 kelereng dibagi rata ke 6 anak. Tiap anak dapat berapa?','','["8","6","9","10"]',2,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','24 buku dibagi rata ke 8 anak. Tiap anak dapat berapa?','','["3","2","8","4"]',0,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 5 = 7','["35","40","30","7"]',0,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 4 = 4','["4","20","12","16"]',3,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 3 = 3','["9","12","3","6"]',0,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 7 = 3','["14","3","21","28"]',2,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','81 ÷ 9 = ?','["9","8","10","11"]',0,'Tanya: dikali berapa supaya dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','36 bunga dibagi rata ke 4 anak. Tiap anak dapat berapa?','','["9","10","4","8"]',0,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 9 = 5','["36","54","45","5"]',2,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','4 mainan dibagi rata ke 2 anak. Tiap anak dapat berapa?','','["2","1","3","4"]',0,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 9 = 9','["81","9","72","90"]',0,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','30 ÷ 5 = ?','["5","8","7","6"]',3,'Tanya: dikali berapa supaya dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa angka yang hilang?','? ÷ 4 = 7','["7","28","24","32"]',1,'Yang hilang = pembagi × hasil.','hard','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','Berapa hasilnya?','40 ÷ 5 = ?','["8","9","7","5"]',0,'Tanya: dikali berapa supaya dapat angka itu?','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_4','21 mainan dibagi rata ke 3 anak. Tiap anak dapat berapa?','','["8","6","7","3"]',2,'Bagi rata = total dibagi banyak anak.','medium','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_5','curriculum',5,'Telaga Pecahan','pecahan',11) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_5';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',7,'Squirtle','Water','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',4,'Charmander','Fire','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',1,'Bulbasaur','Grass','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_5',133,'Eevee','Normal','rare');
DELETE FROM item WHERE zone_id='curriculum_5';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','1/4 + 2/4 = ?','["4/4","3/4","1/4","3/8"]',1,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','3/6 + 2/6 = ?','["5/6","5/12","3/6","6/6"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','1/8 + 5/8 = ?','["6/16","6/8","1/8","7/8"]',1,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','2/4 + 1/4 = ?','["3/8","2/4","4/4","3/4"]',3,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','1/5 + 2/5 = ?','["3/5","3/10","1/5","4/5"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','2/8 − 1/8 = ?','["1/16","3/8","2/8","1/8"]',3,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','7/10 + 2/10 = ?','["9/10","7/10","9/20","10/10"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Mana pecahan yang lebih besar?','3/6   vs   4/6','["3/6","4/6"]',1,'Penyebut sama → pembilang lebih besar = pecahan lebih besar.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','3/5 − 1/5 = ?','["2/10","2/5","3/5","4/5"]',1,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/6 − 3/6 = ?','["2/6","7/6","1/12","1/6"]',3,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/5 − 1/5 = ?','["5/5","3/5","4/5","3/10"]',1,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','6/8 + 1/8 = ?','["7/8","6/8","8/8","7/16"]',0,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','4/10 − 1/10 = ?','["5/10","4/10","3/10","3/20"]',2,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Mana pecahan yang lebih besar?','2/4   vs   3/4','["2/4","3/4"]',1,'Penyebut sama → pembilang lebih besar = pecahan lebih besar.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','3/5 − 2/5 = ?','["1/10","5/5","2/5","1/5"]',3,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Mana pecahan yang lebih besar?','5/8   vs   3/8','["3/8","5/8"]',1,'Penyebut sama → pembilang lebih besar = pecahan lebih besar.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','2/4 − 1/4 = ?','["3/4","1/8","1/4","2/4"]',2,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — kurangkan.','2/6 − 1/6 = ?','["1/6","2/6","1/12","3/6"]',0,'Penyebut sama → pembilang dikurang, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Pecahan berpenyebut sama — jumlahkan.','5/8 + 2/8 = ?','["8/8","5/8","7/8","7/16"]',2,'Penyebut sama → pembilang dijumlah, penyebut tetap.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_5','Mana pecahan yang lebih besar?','2/4   vs   1/4','["1/4","2/4"]',1,'Penyebut sama → pembilang lebih besar = pecahan lebih besar.','easy','');
INSERT INTO zone(id,subject_id,ord,name,topic,min_level) VALUES('curriculum_6','curriculum',6,'Puncak Desimal','desimal',14) ON CONFLICT(id) DO UPDATE SET subject_id=excluded.subject_id,ord=excluded.ord,name=excluded.name,topic=excluded.topic,min_level=excluded.min_level;
DELETE FROM zone_pokemon WHERE zone_id='curriculum_6';
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',25,'Pikachu','Electric','rare');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',63,'Abra','Psychic','uncommon');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',147,'Dratini','Dragon','rare');
INSERT INTO zone_pokemon(zone_id,dex,name,type,rarity) VALUES('curriculum_6',39,'Jigglypuff','Fairy','uncommon');
DELETE FROM item WHERE zone_id='curriculum_6';
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.9 − 0.8 = ?','["1.7","0.0","0.1","0.2"]',2,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.6 = ?','["1.8","0.8","0.7","0.9"]',1,'Sejajarkan koma; jumlahkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.3 − 0.1 = ?','["0.1","0.2","0.3","0.4"]',1,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.8 − 0.1 = ?','["0.7","0.9","0.8","0.6"]',0,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.6 − 0.5 = ?','["0.0","0.1","1.1","0.2"]',1,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.4 − 0.1 = ?','["0.5","0.4","0.2","0.3"]',3,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Mana desimal yang lebih besar?','0.5   vs   0.8','["0.5","0.8"]',1,'Bandingkan angka di belakang koma.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.6 + 0.3 = ?','["0.9","1.9","1.0","0.8"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.9 − 0.3 = ?','["1.2","0.7","0.6","0.5"]',2,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Mana desimal yang lebih besar?','0.6   vs   0.1','["0.6","0.1"]',0,'Bandingkan angka di belakang koma.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.7 − 0.2 = ?','["0.9","0.6","0.5","0.4"]',2,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Mana desimal yang lebih besar?','0.7   vs   0.2','["0.2","0.7"]',1,'Bandingkan angka di belakang koma.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.9 − 0.2 = ?','["0.6","0.7","0.8","1.1"]',1,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.5 − 0.3 = ?','["0.2","0.8","0.1","0.3"]',0,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.5 + 0.7 = ?','["1.3","1.1","2.2","1.2"]',3,'Sejajarkan koma; jumlahkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.9 = ?','["1.0","1.1","1.2","2.1"]',1,'Sejajarkan koma; jumlahkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Jumlahkan desimal berikut.','0.2 + 0.7 = ?','["0.9","1.0","0.8","1.9"]',0,'Sejajarkan koma; jumlahkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Mana desimal yang lebih besar?','0.6   vs   0.8','["0.6","0.8"]',1,'Bandingkan angka di belakang koma.','easy','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Kurangkan desimal berikut.','0.2 − 0.1 = ?','["0.1","0.3","0.0","0.2"]',0,'Sejajarkan koma; kurangkan per tempat desimal.','medium','');
INSERT INTO item(zone_id,q,expr,opts_json,a,hint,difficulty,knowledge) VALUES('curriculum_6','Mana desimal yang lebih besar?','0.8   vs   0.3','["0.8","0.3"]',0,'Bandingkan angka di belakang koma.','easy','');
INSERT INTO content_version(subject_id,built_at,agent,source_notes,status) VALUES('curriculum','2026-06-09T01:26:06.965Z','content-engine','seed.mjs from tools/content-engine/out-math/','active');
COMMIT;